filetype off
call pathogen#infect()
syntax on
filetype plugin indent on
:set expandtab
:set tabstop=4
:retab
:set shiftwidth=4 

map <C-n> :NERDTreeToggle<CR>


let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplModSelTarget = 1

" <F7> to re-indent the whole file
map <F7> mzgg=G`z<CR>

" Map the W to w on write for accidental shift
cnoreabbrev <expr> W ((getcmdtype() is# ':' && getcmdline() is# 'W')?('w'):('W'))

colorscheme molokai
set omnifunc=syntaxcomplete#Complete
